// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM2aXQtoeQDggPQMGwy8b6Z7XwksKDDeY',
    appId: '1:758457706847:web:50e3d4bf621fed2086aeea',
    messagingSenderId: '758457706847',
    projectId: 'final-9488b',
    authDomain: 'final-9488b.firebaseapp.com',
    storageBucket: 'final-9488b.appspot.com',
    measurementId: 'G-1FG6H1VV7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMjFrAazvTiblMEHmenpGz8NDkHqh1cHY',
    appId: '1:758457706847:android:7b33b7ee12a42dc286aeea',
    messagingSenderId: '758457706847',
    projectId: 'final-9488b',
    storageBucket: 'final-9488b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1q5w9YDIWAccwjuxmb2bRUifyAa91pi0',
    appId: '1:758457706847:ios:08c31d212fb898ca86aeea',
    messagingSenderId: '758457706847',
    projectId: 'final-9488b',
    storageBucket: 'final-9488b.appspot.com',
    iosBundleId: 'com.example.final1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1q5w9YDIWAccwjuxmb2bRUifyAa91pi0',
    appId: '1:758457706847:ios:49f68c5a1cdb9a2f86aeea',
    messagingSenderId: '758457706847',
    projectId: 'final-9488b',
    storageBucket: 'final-9488b.appspot.com',
    iosBundleId: 'com.example.final1.RunnerTests',
  );
}
